# Pandas: Filtering - Using conditionals to filter dataframes

## Table of contents

* [View only specific columns](#View-only-specific-columns)
* [Filter rows where ...](#Filter-rows-where-...)
* [Using AND (&), OR (|) and NOT(~) operators for filtering](#Using-AND-(&),-OR-(|)-and-NOT(~)-operators-for-filtering)
* [Where value is in specified iterable (`list`/`tuple`), `Series`, `DataFrame` or `dict`](#Where-value-is-in-specified-iterable-(list/tuple),-Series,-DataFrame-or-dict)
    * [`pandas.DataFrame.isin(<values>)` method](#pandas.DataFrame.isin(<values>)-method)
        * [When *values* is a `list`](#When-values-is-a-list)
        * [When *values* is a `dict`](#When-values-is-a-dict)
        * [When *values* is a `Series` or `DataFrame`](#When-values-is-a-Series-or-DataFrame)
    * [`pandas.Series.isin(<values>)` method](#pandas.Series.isin(<values>)-method)
* [Where Value Is/Not null (NaN)](#Where-Value-Is/Not-null-(NaN))
    * [`pandas.notnull(<obj>)` or `<obj>.notnull()` method](#pandas.notnull(<obj>)-or-<obj>.notnull()-method)
    * [`pandas.isnull(<obj>)` or `<obj>.isnull()` method](#pandas.isnull(<obj>)-or-<obj>.isnull()-method)
* [Where value contains a string](#Where-value-contains-a-string)
* [Now, let's go back to the stack overflow dataset and work with it](#Now,-let's-go-back-to-the-stack-overflow-dataset-and-work-with-it)

***

In [260]:
people = {
    "first_name": ["Nabeel", "Jane", "John"],
    "last_name": ["Malik", "Doe", "Doe"],
    "email": ["nabeel_malik@email.com", "jane_doe@email.com", "john_doe@email.com"]
}

In [261]:
import pandas as pd
df_from_dict = pd.DataFrame(people)

In [262]:
df_from_dict

  first_name last_name                   email
0     Nabeel     Malik  nabeel_malik@email.com
1       Jane       Doe      jane_doe@email.com
2       John       Doe      john_doe@email.com

## View only specific columns

The most basic way to filter is one we have already looked at, to view specific columns:

In [263]:
df_from_dict['last_name']

0    Malik
1      Doe
2      Doe
Name: last_name, dtype: object

## Filter rows where ...

Now, let's say we want to filter rows with the last name *'Doe'*:

In [264]:
df_from_dict['last_name'] == 'Doe'              # Will return a boolean Series

0    False
1     True
2     True
Name: last_name, dtype: bool

This returns a **boolean Series** indicating which *rows* meet, and which do not meet our filter criteria.

This is a **filter mask**, and when you apply it to a dataframe, it will give you all the rows that meet that criteria.

This **filter mask** can be applied to a dataframe in a couple of ways:

1. By passing the **boolean Series** directly into the **dataframe `[]`** like we are searching for a column:

In [265]:
df_from_dict[df_from_dict['last_name'] == 'Doe']

  first_name last_name               email
1       Jane       Doe  jane_doe@email.com
2       John       Doe  john_doe@email.com

2. By passing the **boolean Series** into the `.loc` **indexer** (remember that `.iloc` and `.loc` indexers can take *boolean arrays* as input):

In [266]:
df_from_dict.loc[df_from_dict['last_name'] == 'Doe']

  first_name last_name               email
1       Jane       Doe  jane_doe@email.com
2       John       Doe  john_doe@email.com

The reason that the 2nd method above is preferred is because with `.loc` we can still grab sepcific columns if we want (since the first argument to the `.loc` indexer is already applied as a 'row filter'):

In [267]:
df_from_dict.loc[df_from_dict['last_name'] == 'Doe', 'email']

1    jane_doe@email.com
2    john_doe@email.com
Name: email, dtype: object

## Using AND (&), OR (|) and NOT(~) operators for filtering

In [268]:
df_from_dict

  first_name last_name                   email
0     Nabeel     Malik  nabeel_malik@email.com
1       Jane       Doe      jane_doe@email.com
2       John       Doe      john_doe@email.com

Let's say we want our filter to return all the rows with the *last_name: Doe* **AND** *first_name: John*:

In [269]:
df_from_dict.loc[(df_from_dict['last_name'] == 'Doe') & (df_from_dict['first_name'] == 'John')]

  first_name last_name               email
2       John       Doe  john_doe@email.com

Note, that the 2 sets of inner `()` are not needed, but are added for clarity.

Now, let's say we want our filter to return all the rows with the *last_name: Malik* **OR** *first_name: John*:

In [270]:
df_from_dict.loc[(df_from_dict['last_name'] == 'Malik') | (df_from_dict['first_name'] == 'John')]

  first_name last_name                   email
0     Nabeel     Malik  nabeel_malik@email.com
2       John       Doe      john_doe@email.com

Now, let's say we want the complete opposite of the filter above, we can simply add the **NOT** operator, `~` before the filter:

In [271]:
df_from_dict.loc[~((df_from_dict['last_name'] == 'Malik') | (df_from_dict['first_name'] == 'John'))]

  first_name last_name               email
1       Jane       Doe  jane_doe@email.com

Note that we have added another set of `()` on the entire filter to apply the `~` operator to it.

Sometimes it is better for code legibility to save the filter (that is a **boolean Series**) to a *variable*, and then pass that *variable* into the `.loc` indexer of a dataframe.

In [272]:
filt = (df_from_dict['last_name'] == 'Malik') | (df_from_dict['first_name'] == 'John')
df_from_dict.loc[~filt]

  first_name last_name               email
1       Jane       Doe  jane_doe@email.com

## Where value is in specified iterable (`list`/`tuple`), `Series`, `DataFrame` or `dict`

The `.isin()` method can be called on both, **DataFrame** and **Series** objects.

### `pandas.DataFrame.isin(<values>)` method

> **Parameters**: *values*: iterable(`list`/`tuple`), `Series`, `DataFrame` or `dict`.

> **Returns**: boolean `DataFrame`.

When called on a `DataFrame`, the `.isin()` *method* returns a **boolean** `DataFrame` showing whether each element in the `DataFrame` is contained in *values*.

The result will only be true at a location if all the labels match. 

> If values is a `Series`, that’s the index.

> If values is a `dict`, the *keys* must be the column names, which must match. 

> If values is a `DataFrame`, then both the index and column labels must match.

#### When *values* is a `list`

In [273]:
df_a = pd.DataFrame({'A': [1, 2, 3], 'B': ['a', 'b', 'f']})
df_a

   A  B
0  1  a
1  2  b
2  3  f

In [274]:
df_a.isin([1, 3, 12, 'a'])

       A      B
0   True   True
1  False  False
2   True  False

In [275]:
type(df_a.isin([1, 3, 12, 'a']))

pandas.core.frame.DataFrame

#### When *values* is a `dict`

In [276]:
df_b = pd.DataFrame({'A': [1, 2, 3], 'B': [1, 4, 7]})
df_b

   A  B
0  1  1
1  2  4
2  3  7

In [277]:
df_b.isin({'A': [1, 3], 'B': [4, 7, 12]})

       A      B
0   True  False
1  False   True
2   True   True

#### When *values* is a `Series` or `DataFrame`

In [278]:
df_c = pd.DataFrame({'A': [1, 2, 3], 'B': ['a', 'b', 'f']})
other = pd.DataFrame({'A': [1, 3, 3, 2], 'B': ['e', 'f', 'f', 'e']})

In [279]:
df_c

   A  B
0  1  a
1  2  b
2  3  f

In [280]:
other

   A  B
0  1  e
1  3  f
2  3  f
3  2  e

In [281]:
df_c.isin(other)

       A      B
0   True  False
1  False  False
2   True   True

Note: since the *values* is a `DataFrame`, we get a *True* only when both, the index and column labels, match.

### `pandas.Series.isin(<values>)` method

> **Parameters**: *values*: `set` or `list`-like.

> **Returns**: boolean `Series`.

When called on a `Series`, the `.isin()` *method* returns a **boolean** `Series` showing whether each element in the `Series` is contained in *values*.

In [282]:
df_d = pd.DataFrame({'A': [1, 2, 3], 'B': ['a', 'b', 'f']})
df_d

   A  B
0  1  a
1  2  b
2  3  f

In [283]:
df_d['B'].isin(['a', 'f'])

0     True
1    False
2     True
Name: B, dtype: bool

In [284]:
type(df_d['B'].isin(['a', 'f']))

pandas.core.series.Series

Futher reading on `pandas.DataFrame.isin()` *method*:<br>https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.isin.html

Futher reading on `pandas.Series.isin()` *method*:<br>https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html

## Where Value Is/Not null (NaN)

### `pandas.notnull(<obj>)` or `<obj>.notnull()` method

> **Parameters**: *obj*: array-like or object value.

> **Returns**: For scalar input, returns a scalar boolean. For array input, returns a boolean array.

This method is used to detect non-missing values for an array-like object.

In [285]:
df_e = pd.DataFrame({'A': [1, 2, 3], 'B': ['a', None, 'f']})
df_e

   A     B
0  1     a
1  2  None
2  3     f

In [286]:
pd.notnull(df_e)

      A      B
0  True   True
1  True  False
2  True   True

In [287]:
df_e.notnull()

      A      B
0  True   True
1  True  False
2  True   True

Note: The above 2 commands return the same **boolean DataFrame**. They are just different ways to apply the same method.

The `.notnull()` method can also be applied to a **Series** object to create a **boolean Series** that can be used as a filter for a **DataFrame**.

In [288]:
df_e[df_e['B'].notnull()]

   A  B
0  1  a
2  3  f

In [289]:
df_e.loc[df_e['B'].notnull()]

   A  B
0  1  a
2  3  f

### `pandas.isnull(<obj>)` or `<obj>.isnull()` method

`.isnull()` works in exactly the same manner as `.notnull()`, except that it has the reverse logic of `.notnull()`.

## Where value contains a string

We can also use **string methods** as filters in **pandas**.

In [290]:
df_employee = pd.DataFrame({'Name': ['John', 'Omar', 'Carol'], 'Languages': ['English', 'English;Arabic', 'Swedish;French']})
df_employee

    Name       Languages
0   John         English
1   Omar  English;Arabic
2  Carol  Swedish;French

If we want to find all the employees *that know 'English'*:

In [291]:
lang_filter = df_employee['Languages'].str.contains('English', na=False)

In [292]:
df_employee.loc[lang_filter]

   Name       Languages
0  John         English
1  Omar  English;Arabic

***

## Now, let's go back to the stack overflow dataset and work with it

In [293]:
df = pd.read_csv('work_directory/pandas/data/survey_results_public.csv', index_col='Respondent')
df_schema = pd.read_csv('work_directory/pandas/data/survey_results_schema.csv', index_col='Column')

In [294]:
pd.set_option('display.max_rows', 85)
pd.set_option('display.max_columns', 85)

In [295]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

Now, if we want to filter for respondents with **salaries higher than 70000**:

In [296]:
high_salary_filt = df['ConvertedComp'] > 70000

In [297]:
df.loc[high_salary_filt]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,Taken an online course in programming or softw...,NaN,Data or business analyst;Data scientist or mac...,13,15,3,Very satisfied,Slightly satisfied,Very confident,No,Yes,I am not interested in new job opportunities,1-2 years ago,Write any code;Complete a take-home project;In...,No,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,CAD,Canadian dollar,40000.0,Monthly,366420.0,15.0,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,A little above average,No,NaN,"Yes, it's not part of our process but the deve...",Not sure,I have little or no influence,Java;R;SQL,Python;Scala;SQL,MongoDB;PostgreSQL,PostgreSQL,Android;Google Cloud Platform;Linux;Windows,Android;Google Cloud Platform;Linux;Windows,NaN,NaN,Hadoop,Hadoop;Pandas;TensorFlow;Unity 3D,Android Studio;Eclipse;PyCharm;RStudio;Visual ...,Windows,I do not use containers,Not at all,NaN,No,Yes,No,YouTube,In real life (in person),Login,2011,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult
9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Database administrator;Developer, back-end;Dev...",12,11,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Interview with people in peer r...,Yes,Financial performance or funding status of the...,I was preparing for a job search,NZD,New Zealand dollar,138000.0,Yearly,95179.0,32.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's not part of our process but the deve...",Not sure,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ru...,DynamoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,AWS;Docker;Heroku;Linux;MacOS;Slack,AWS;Docker;Heroku;Linux;MacOS;Slack;Other(s):,Express;Ruby on Rails;Other(s):,Express;Ruby on Rails;Other(s):,Node.js;Unity 3D,Node.js,Vim,MacOS,Development;Testing;Production,Not at all,An irresponsible use of resources,No,SIGH,Yes,Twitter,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Complete a take-home project;Interview with pe...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,90000.0,Yearly,90000.0,40.0,There is a schedule and/or spec (made by me or...,"Meetings;Non-work commitments (parenting, scho...",All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust...,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Lin...,Android;AWS;Docker;IBM Cloud or Watson;Linux;S...,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Express;Vue.js,Node.js;Xamarin,Node.js;TensorFlow,Vim;Visual Studio;Visual Studio Code;Xcode,Windows,Development;Testing;Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2011,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",10,17,3,Very satisfied,Slightly satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",3-4 years ago,Interview with people in senior / management r...,Yes,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,GBP,Pound sterling,29000.0,Monthly,455352.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,A few days each month,Home,Average,No,NaN,"No, but I think we should",Developers and management have nearly equal in...,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,C#;HTML/CSS;JavaScript;TypeScript;WebAssembly;...,MongoDB;Microsoft SQL Server;MySQL,Elasticsearch;MongoDB;Microsoft SQL Server;SQLite,NaN,AWS;Google Cloud Platform;Microsoft Azure,Angular/Angular.js;ASP.NET;jQuery,Angular/Angular.js;ASP.NET;React.js,.NET;.NET Core;Node.js,.NET Core;Node.js;React Native,Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,A passing fad,No,SIGH,No,YouTube,Online,Username,2010,Multiple times per day,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,NaN,Taken an online course in programming or softw...,"10,000 or more employees","Data or business analyst;Designer;Developer, b...",35,12,18,Slightly satisfied,Very dissatisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Financial perf...,I had a negative experience or interaction at ...,USD,United States dollar,103000.0,Yearly,103000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,"Less than half the time, but at least one day ...",Home,Average,No,NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Elasticsearch;MySQL;Oracle;Redis,Elasticsearch;MySQL;Oracle;Redis,Docker;Linux;Raspberry Pi;Windows,Docker;Linux;Raspberry Pi;Windows,Angular/Angular.js;Ruby on Rails,Angular/Angular.js;Ruby on Rails,Node.js,Node.js,Sublime Text;Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Not at all,NaN,Yes,Yes,Yes,Instagram,Online,Username,I don't remember,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",20 to 99 employees,"Developer, back-end;Developer, full-stack;Educ...",9,12,7,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Financial performance or funding status of the...,I was preparing for a job search,USD,United States dollar,114000.0,Yearly,114000.0,55.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Non-work commitme...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",2.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have some influence,HTML/CSS;JavaScript;Ruby;SQL;Other(s):,Elixir;Ruby;SQL;Other(s):,Firebase;MongoDB;PostgreSQL,MongoDB;PostgreSQL;Other(s):,Docker;Heroku,Docker;Google Cloud Platform;Heroku;Kubernetes,Express;React.js;Ruby on Rails,Ruby on Rails,Node.js,NaN,RubyMine;Visual Studio Code,MacOS,Development;Testing;Production,Non-currency applications of blockchain,An irresponsible use of resources,Yes,SIGH,Yes,Twitter,In real life (in person),Username,2009,Multiple times per day,Find answers to specific questions;Contribute ...,1-2 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,A few times per week,Yes,Yes,Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
39984,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,100 to 499 employees,"Developer, back-end",11,15,5,Very satisfied,Very satisfied,Very confident,No,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",Yes,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,USD,United States dollar,115000.0,Yearly,115000.0,35.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,"Less than half the time, but at least one day ...",Home,A little above average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have some influence,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,Bash/Shell/PowerShell;Java;SQL,Elasticsearch;MongoDB;MySQL;Oracle;Redis,MySQL;Redis,AWS;Docker;Google Cloud Platform;Kubernetes;Li...,AWS;Docker;Kubernetes;Linux;MacOS;Slack,Angular/Angular.js;jQuery;Spring,Spring,NaN,NaN,IntelliJ;Vim,MacOS,Development;Testing;Production;Outside of work...,Non-currency applications of blockchain,A passing fad,Yes,Also Yes,Yes,Reddit,In real life (in person),NaN,2010,Multiple times per day,Find answers to specific questions,6-10 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,NaN,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Easy
39985,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"1,000 to 4,999 employees","Developer, front-end",12,16,10,Slightly satisfied,Neither satisfied nor dissatisfied,Not at all confident,Not sure,No,I am not interested in new job opportunities,Less than a year ago,Complete a take-home project;Interview with pe...,Yes,Office environment or company culture;Diversit...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,160000.0,Yearly,160000.0,45.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Toxic wo...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,Dart;HTML/CSS;Kotlin;TypeScript;WebAssembly,NaN,NaN,MacOS;Slack;Windows,Android;MacOS;Slack;Windows,jQuery;React.js;Ruby on Rails,React.js,Node.js,Flutter,Visual Studio Code,MacOS,I do not use containers,Not at all,An irresponsible use of resources,No,SIGH,Yes,Twitter,Online,Username,2008,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Courses on technologies you're interested in,32.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Neither easy nor difficult
39991,"I am not primarily a developer, but I write co...",No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",United Kingdom,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...","Engineer, data",35,12,20,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",NA - I am an independent contractor or self em...,NaN,No,Specific department or team I'd be working on;...,I heard about a job opportunity (from a recrui...,GBP,Pound sterling,65000.0,Yearly,85051.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Time spent com...,It's complicated,Home,Average,No,NaN,NaN,NaN,NaN,SQL,Python;SQL,Microsoft SQL Server,Microsoft SQL Server;Oracle;SQLite,Windows,Windows,NaN,NaN,NaN,Pandas,Visual Studio,Windows,I do not use containers,NaN,NaN,Yes,Yes,Yes,LinkedIn,In real life (in person),Username,NaN,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,49.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
39993,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,"1,000 to 4,999 employees","Developer, back-end",5,18,Less than 1 year,Very dissatisfied,Very dissatisfied,Not at all confident,No,No,"I’m not actively looking, but I am open to new...",Less than a year ago,Solve a brain-teaser style puzzle;Interview wi...,No,Specific department or team I'd be working on;...,I was preparing for a job search,USD,United States dollar,80000.0,Yearly,80000.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Lack of...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",2.0,"Yes, it's part of our process",Not sure,I have little or no influence,Bash/Shell/PowerShell;Java;JavaScript;Python;S...,Bash/Shell/PowerShell;C;Dart;Elixir;Go;Python,Other(s):,DynamoDB;Elasticsearch;MySQL;Other(s):,AWS;Linux;Slack;Windows,AWS;Google Cloud Platform;Linux;MacOS;Slack,NaN,NaN,Ansible;Apache Spark;Hadoop;Pandas,Apache Spark;Hadoop;Pandas;TensorFlow;Torch/Py...,Eclipse;Vim;Visual Studio Code,Windows,I do not use containers,Not at all,An irresponsible use of resources,Yes,SIGH,Yes,Reddit,Neither,Username,2014,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,60+ minutes,Not sure / can't remember,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy

Now, instead of seeing all the columns, if we want to **see only the Country, Salary and Languages for the respondents** with high salaries filtered above:

In [298]:
df.loc[high_salary_filt, ['Country', 'ConvertedComp', 'LanguageWorkedWith']]

,Country,ConvertedComp,LanguageWorkedWith
Respondent,,,
6,Canada,366420.0,Java;R;SQL
9,New Zealand,95179.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...
13,United States,90000.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...
16,United Kingdom,455352.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...
22,United States,103000.0,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...
...,...,...,...
39974,United States,114000.0,HTML/CSS;JavaScript;Ruby;SQL;Other(s):
39984,United States,115000.0,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
39985,United States,160000.0,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
39991,United Kingdom,85051.0,SQL
39993,United States,80000.0,Bash/Shell/PowerShell;Java;JavaScript;Python;S...

Now, what if we want to modify the filter on the dataframe above, such that, in addition to all the currently applied filters, we want to look at the respondents from *only* the **following countries: United States, India, United Kingdom, Germany, and Canada.**

This can be achieved using the `.isin()` *method*.

In [299]:
countries = ['United States', 'India', 'United Kingdom', 'Germany', 'Canada']

In [300]:
country_filt = df['Country'].isin(countries)

In [301]:
df.loc[high_salary_filt & country_filt, ['Country', 'ConvertedComp', 'LanguageWorkedWith']]

,Country,ConvertedComp,LanguageWorkedWith
Respondent,,,
6,Canada,366420.0,Java;R;SQL
13,United States,90000.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...
16,United Kingdom,455352.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...
22,United States,103000.0,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...
26,United States,114000.0,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...
...,...,...,...
39974,United States,114000.0,HTML/CSS;JavaScript;Ruby;SQL;Other(s):
39984,United States,115000.0,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
39985,United States,160000.0,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
39991,United Kingdom,85051.0,SQL
39993,United States,80000.0,Bash/Shell/PowerShell;Java;JavaScript;Python;S...

Now, we want add a filter, to the existing filters, for respondents **that know 'Python' as a programming language:**

In [302]:
lang_filt = df['LanguageWorkedWith'].str.contains('Python', na=False)

In [303]:
df.loc[high_salary_filt & country_filt & lang_filt, ['Country', 'ConvertedComp', 'LanguageWorkedWith']]

,Country,ConvertedComp,LanguageWorkedWith
Respondent,,,
22,United States,103000.0,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...
26,United States,114000.0,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...
32,United States,1100000.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...
45,United States,175000.0,Python
60,United States,107000.0,Bash/Shell/PowerShell;Go;JavaScript;PHP;Python...
...,...,...,...
39923,United States,102000.0,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...
39955,United States,111600.0,Bash/Shell/PowerShell;C;C++;Go;HTML/CSS;Java;J...
39968,United States,215000.0,Java;Python;Scala
39970,United States,218000.0,PHP;Python;SQL
39993,United States,80000.0,Bash/Shell/PowerShell;Java;JavaScript;Python;S...